language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"

script:
  - pip install coverage
  - pip install coveralls
  - coverage run setup.py test
  - coverage report --include=delta* --show-missing --fail-under 100

after_success:
  - coveralls
